apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-boot
  namespace: default
spec:
  source:
    git:
      ref:
        branch: master
      url: https://github.com/kdvolder/hello-boot