apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdemo
spec:
  selector:
    matchLabels:
      app: webdemo
  replicas: 1
  template:
    metadata:
      labels:
        app: webdemo    
    spec:
     containers:
       - name: webdemo
         image: kdvolder/k8s-web-demo
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 8080